#!/usr/bin/env python3
"""Dump every frame the Python client can send, for the server's conformance test.

`protocol/PROTOCOL.md`, `server/src/protocol.ts` and
`client/src/yammer_client/protocol.py` are three views of one contract, and
AGENTS.md is blunt about the consequence: a mismatch between the implementations
will not show up as a type error. Nothing checks them against each other.

This is the missing check, in the only form that actually proves anything — the
frames are produced by the *real* client module, and the server's test suite
decodes them with its *real* decoder. A TypeScript test that builds its own
JSON and then parses it proves only that JSON round-trips.

`Protocol.kt` makes four views. It should be held to the same fixture.

Usage:
    cd client
    .venv/bin/python tools/dump_protocol_frames.py
"""

from __future__ import annotations

import json
from pathlib import Path

import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from yammer_client import protocol  # noqa: E402

# Fixed arguments, so regenerating without a protocol change produces no diff.
TURN = 7
REQUEST_ID = "per_ff18c0de"


def main() -> int:
    out_dir = Path(__file__).resolve().parents[2] / "fixtures" / "protocol"
    out_dir.mkdir(parents=True, exist_ok=True)

    fixture = {
        "$comment": (
            "Generated by client/tools/dump_protocol_frames.py from the real "
            "Python client protocol module. Do not hand-edit. Consumed by "
            "server/src/protocol.test.ts."
        ),
        "generator": "client/tools/dump_protocol_frames.py",
        "constants": {
            "protocolVersion": protocol.PROTOCOL_VERSION,
            "clientId": protocol.CLIENT_ID,
            "captureFormat": protocol.CAPTURE_FORMAT.to_json(),
            "defaultSpeechFormat": protocol.DEFAULT_SPEECH_FORMAT.to_json(),
            "closeCodes": {
                "AUTH_FAILED": protocol.CloseCode.AUTH_FAILED,
                "UNSUPPORTED_PROTOCOL": protocol.CloseCode.UNSUPPORTED_PROTOCOL,
                "PROTOCOL_VIOLATION": protocol.CloseCode.PROTOCOL_VIOLATION,
            },
        },
        # Verbatim wire text, not a re-serialization: whatever the client would
        # actually put on the socket.
        "controlFrames": {
            "hello": protocol.hello("s3cret-token"),
            "utterance.begin": protocol.utterance_begin(TURN),
            "utterance.end": protocol.utterance_end(TURN),
            "utterance.cancel": protocol.utterance_cancel(TURN, "restart"),
            "answer.begin": protocol.answer_begin(TURN, REQUEST_ID),
            "answer.end": protocol.answer_end(TURN, REQUEST_ID),
            "answer.timeout": protocol.answer_timeout(TURN, REQUEST_ID),
        },
        # turn tag + PCM, hex-encoded. The wraparound case is included because
        # `turn` is a uint32 that the spec says wraps, and a signed-int bug in
        # any implementation only ever shows up there.
        "audioFrames": [
            {"turn": 0, "pcmHex": "", "frameHex": protocol.encode_audio_frame(0, b"").hex()},
            {
                "turn": TURN,
                "pcmHex": "0100feff7f0080ff",
                "frameHex": protocol.encode_audio_frame(
                    TURN, bytes.fromhex("0100feff7f0080ff")
                ).hex(),
            },
            {
                "turn": 4294967295,
                "pcmHex": "abcd",
                "frameHex": protocol.encode_audio_frame(
                    4294967295, bytes.fromhex("abcd")
                ).hex(),
            },
        ],
        # Frames the server must reject with a protocol violation rather than
        # tolerate. Kept here rather than in the TS test so all three (four)
        # implementations can be held to the same list.
        "rejected": [
            {"why": "not JSON", "raw": "{"},
            {"why": "not an object", "raw": "[1,2,3]"},
            {"why": "no type tag", "raw": '{"turn":7}'},
            {"why": "unknown type", "raw": '{"t":"utterance.pause","turn":7}'},
            {"why": "hello.proto not a number", "raw": '{"t":"hello","proto":"2","token":"x"}'},
            {"why": "hello.token missing", "raw": '{"t":"hello","proto":2}'},
            {"why": "turn not an integer", "raw": '{"t":"utterance.begin","turn":1.5}'},
            {"why": "turn negative", "raw": '{"t":"utterance.begin","turn":-1}'},
            {"why": "answer id empty", "raw": '{"t":"answer.begin","turn":7,"id":""}'},
            {"why": "answer id missing", "raw": '{"t":"answer.end","turn":7}'},
        ],
    }

    out_path = out_dir / "client-frames.json"
    out_path.write_text(json.dumps(fixture, indent=1) + "\n")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
